### ISSUE TITLE
Bee "lock" doesn't stay in place

### ISSUE THREAD

**Issue by Luminnox** [Dans-Plugins/Wild-Pets#261]
**Describe the bug**
As the Title says the bee continues having its Vanilla AI behaviour.

**To Reproduce**
1. Spawn Bee
2. Tame Bee
3. /wp lock (already selected)
4. Continues to having its Vanilla Ai behaviour.

**Expected behavior**
That the bee stays in it's place

Paper, MC 1.19.4

**Additional context**
Also, the follow doesn't work as expected. The Bee continues with its Ai behaviour and occasionally teleports back to the player.

No Error Codes in Console.

**Comment by dmccoystephenson** [comment]
Locking pets prevents others from interacting them, it doesn't prevent them from moving. Sorry for the confusion!

There used to be a stay command, but it was extremely laggy so it was removed.
