### ISSUE TITLE
Prevent pets from causing damage to players

### ISSUE THREAD

**Issue by FeralBloom** [Dans-Plugins/Wild-Pets#262]
## Description
**Describe the bug**
After I tamed a phantom it continued to act like a normal phantom and keeps biting me.

**To Reproduce**
1. Type /wp tame
2. Right-click a phantom with a stack of soulsand in hand
3. Stand and wait for your new "pet" to kill you

**Expected behavior**
I expected the phantom to stop swooping and biting me or at least to stop dealing damage to me.

**Additional context**
I will love him no matter what but the biting is not fun

## Acceptance Criteria
- [x] Cancel damage directly from pets (i.e. zombie melee attacks)
- [x] Cancel damage from projectiles shot by pets (i.e. skeletons)
- [x] Cancel damage from potions thrown by pets (i.e. witches)

**Comment by dmccoystephenson** [comment]
Preventing the targeting behavior has proven difficult in the past, but I bet we could prevent damage. I'll look into this :)

**Comment by dmccoystephenson** [comment]
I have added a check to the plugin to prevent pets from damaging entities directly. This does not account for projectiles or potions, but this is planned. Please feel free to contact me on Discord if you want a pre-release JAR with these changes.
